---

name: Differential Linters

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v4

      - id: VCS_Diff_Lint
        name: VCS Diff Lint
        uses: fedora-copr/vcs-diff-lint-action@v1

      - if: ${{ always() }}
        name: Upload artifact with detected defects in SARIF format
        uses: actions/upload-artifact@v3
        with:
          name: VCS Diff Lint SARIF
          path: ${{ steps.VCS_Diff_Lint.outputs.sarif }}

      - if: ${{ always() }}
        name: Upload SARIF to GitHub using github/codeql-action/upload-sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.VCS_Diff_Lint.outputs.sarif }}

...
